CREATE DATABASE IF NOT EXISTS {!database};
USE {!database};

CREATE TABLE IF NOT EXISTS User (
    Email NVARCHAR(255) NOT NULL,
    Phone NVARCHAR(32),
    FirstName NVARCHAR(255),
    LastName NVARCHAR(255),
    EmailVerified BOOLEAN DEFAULT FALSE,
    IsActive BOOLEAN DEFAULT TRUE,
    ActivatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (Id)
) CHARACTER SET utf8mb4;

CREATE UNIQUE INDEX IF NOT EXISTS UserEmail ON User(Email);

CREATE TABLE IF NOT EXISTS UserCredentialType (
    Value NCHAR(32) NOT NULL,
    PRIMARY KEY (Value)
) CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS UserCredential (
    Value VARCHAR(4096) NOT NULL,
    UserId CHAR(255) NOT NULL,
    Type NCHAR(32) NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    ExpirationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT CredentialUser
        FOREIGN KEY (UserId) REFERENCES User(Id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT,
    CONSTRAINT UserCredentialType
        FOREIGN KEY (Type) REFERENCES UserCredentialType(Value)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    PRIMARY KEY (Id)
) CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS Organization (
    Name NVARCHAR(255) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    PRIMARY KEY (Id)
) CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS OrganizationRole (
    Name NVARCHAR(255) NOT NULL,
    Label NVARCHAR(255) NOT NULL,
    OrganizationId CHAR(255) NOT NULL,
    PRIMARY KEY (Id)
) CHARACTER SET utf8mb4;

CREATE UNIQUE INDEX IF NOT EXISTS RoleNameWithinOrg ON OrganizationRole(Name, OrganizationId);

CREATE TABLE IF NOT EXISTS OrganizationUser (
    OrganizationId CHAR(255) NOT NULL,
    UserId CHAR(255) NOT NULL,
    RoleId CHAR(255) NOT NULL,
    CONSTRAINT OrganizationUserOrganization
        FOREIGN KEY (OrganizationId) REFERENCES Organization(Id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT,
    CONSTRAINT OrganizationUserUser
        FOREIGN KEY (UserId) REFERENCES User(Id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT,
    CONSTRAINT OrganizationUserRole
        FOREIGN KEY (RoleId) REFERENCES OrganizationRole(Id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT,
    PRIMARY KEY (OrganizationId, UserId)
) CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS Post (
    AuthorId CHAR(255) NOT NULL,
    Status NVARCHAR(64) NOT NULL,
    Slug NVARCHAR(64) NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    Body NVARCHAR(32768) NOT NULL,
    CONSTRAINT PostAuthor
        FOREIGN KEY (AuthorId) REFERENCES User(Id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT,
    PRIMARY KEY (Id)
) CHARACTER SET utf8mb4;

CREATE UNIQUE INDEX IF NOT EXISTS PostSlug ON Post(Slug);